[package]
name = "llhd-objcopy"
version = "0.1.0"
authors = ["Andreas Traber <andytraber@gmail.com>"]

repository = "https://github.com/atraber/llhd-objcopy"
license = "MIT"

[dependencies]
llhd = "0.1"
argparse = "0.2.1"
